"""
Publisher Agent — LangGraph output chain for report generation.
Receives structured JSON analysis from Analyst Agent.
Formats into clean markdown report.
Prints to console + saves to file.
Deployed as an independent Bindu microservice.
"""

import json
import os
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI

from bindu.penguin.bindufy import bindufy

load_dotenv(override=True)
# ── LLM ───────────────────────────────────────────────────────────────────────
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=os.getenv("GOOGLE_API_KEY"),
    temperature=0.2,
)

# ── Prompt ────────────────────────────────────────────────────────────────────
publish_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a professional technical writer. 
Your job is to transform structured analysis JSON into a clean, readable markdown report.

The report must follow this exact structure:

# [Theme as Title]

## Summary
[2-3 sentence summary]

## Key Findings
[Each claim as a bullet point with its confidence level in brackets]

## Analysis Quality
[Overall quality assessment with reasoning]

---
*Generated by Bindu NightSky Swarm*

Use clear, professional language. No fluff. No extra sections."""
    ),
    (
        "human",
        "Transform this analysis into a markdown report:\n\n{analysis}"
    )
])

# ── Chain ─────────────────────────────────────────────────────────────────────
publish_chain = publish_prompt | llm | StrOutputParser()

# ── Report saving ─────────────────────────────────────────────────────────────
def save_report(report: str, theme: str) -> Path:
    """Save markdown report to reports/ directory with timestamp."""
    reports_dir = Path(__file__).parent / "reports"
    reports_dir.mkdir(exist_ok=True)

    # Clean theme for filename
    safe_theme = "".join(
        c if c.isalnum() or c in " -_" else ""
        for c in theme
    ).strip().replace(" ", "_")[:50]

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}_{safe_theme}.md"
    filepath = reports_dir / filename

    filepath.write_text(report, encoding="utf-8")
    return filepath

# ── Handler ───────────────────────────────────────────────────────────────────
def handler(messages: list[dict[str, str]]) -> str:
    """
    Bindu-compatible handler.
    Receives Analyst's JSON via A2A, publishes formatted markdown report.
    """
    if not messages:
        return "No input received."

    raw_content = messages[-1].get("content", "")
    if not raw_content:
        return "Empty analysis received."

    print(f"\n📤 Publisher Agent — formatting report")

    # Parse incoming JSON from Analyst
    try:
        analysis = json.loads(raw_content)
    except json.JSONDecodeError:
        # If not JSON, treat as raw text
        analysis = {"theme": "Research Report", "summary": raw_content, "claims": []}

    theme = analysis.get("theme", "Research Report")

    try:
        # Generate markdown report via LLM chain
        report = publish_chain.invoke({
            "analysis": json.dumps(analysis, indent=2)
        })

        # Clean up content blocks if Gemini returns list format
        if isinstance(report, list):
            report = " ".join(
                block.get("text", "") if isinstance(block, dict) else str(block)
                for block in report
            ).strip()

        # Print to console
        print("\n" + "="*60)
        print("📄 PUBLISHED REPORT")
        print("="*60)
        print(report)
        print("="*60 + "\n")

        # Save to file
        filepath = save_report(report, theme)
        print(f"💾 Report saved: {filepath}")

        return report

    except Exception as e:
        print(f"❌ Publisher failed: {e}")
        return f"Publishing failed: {str(e)}"


# ── Bindu config ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    config = {
        "author": "nivasm2823@gmail.com",
        "name": "publisher-agent",
        "description": "LangGraph output agent. Formats structured analysis into clean markdown reports and saves to file.",
        "capabilities": {"streaming": False},
        "deployment": {
            "url": "http://localhost:3783",
            "expose": True,
            "protocol_version": "1.0.0",
        },
        "storage": {"type": "memory"},
        "scheduler": {
            "type": "redis",
            "redis_url": os.getenv("REDIS_URL", "redis://localhost:6379"),
        },
    }

    bindufy(config=config, handler=handler)